//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEqlink.DuongTest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCountry", Namespace="http://tempuri.org/", ItemName="country")]
    [System.SerializableAttribute()]
    public class ArrayOfCountry : System.Collections.Generic.List<AutoEqlink.DuongTest.country> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowHorseInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShowHorseInfo {
            get {
                return this.ShowHorseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowHorseInfoField, value) != true)) {
                    this.ShowHorseInfoField = value;
                    this.RaisePropertyChanged("ShowHorseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Flag {
            get {
                return this.FlagField;
            }
            set {
                if ((object.ReferenceEquals(this.FlagField, value) != true)) {
                    this.FlagField = value;
                    this.RaisePropertyChanged("Flag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveTote", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LiveTote : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rowidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceBoardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceCountryOddsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tstampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rowid {
            get {
                return this.rowidField;
            }
            set {
                if ((object.ReferenceEquals(this.rowidField, value) != true)) {
                    this.rowidField = value;
                    this.RaisePropertyChanged("rowid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RaceCard {
            get {
                return this.RaceCardField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceCardField, value) != true)) {
                    this.RaceCardField = value;
                    this.RaisePropertyChanged("RaceCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RaceCountry {
            get {
                return this.RaceCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceCountryField, value) != true)) {
                    this.RaceCountryField = value;
                    this.RaisePropertyChanged("RaceCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RaceDay {
            get {
                return this.RaceDayField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceDayField, value) != true)) {
                    this.RaceDayField = value;
                    this.RaisePropertyChanged("RaceDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RaceBoard {
            get {
                return this.RaceBoardField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceBoardField, value) != true)) {
                    this.RaceBoardField = value;
                    this.RaisePropertyChanged("RaceBoard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RaceCountryOdds {
            get {
                return this.RaceCountryOddsField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceCountryOddsField, value) != true)) {
                    this.RaceCountryOddsField = value;
                    this.RaisePropertyChanged("RaceCountryOdds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RaceNo {
            get {
                return this.RaceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceNoField, value) != true)) {
                    this.RaceNoField = value;
                    this.RaisePropertyChanged("RaceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Win {
            get {
                return this.WinField;
            }
            set {
                if ((object.ReferenceEquals(this.WinField, value) != true)) {
                    this.WinField = value;
                    this.RaisePropertyChanged("Win");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceField, value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string txday {
            get {
                return this.txdayField;
            }
            set {
                if ((object.ReferenceEquals(this.txdayField, value) != true)) {
                    this.txdayField = value;
                    this.RaisePropertyChanged("txday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string events {
            get {
                return this.eventsField;
            }
            set {
                if ((object.ReferenceEquals(this.eventsField, value) != true)) {
                    this.eventsField = value;
                    this.RaisePropertyChanged("events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string info {
            get {
                return this.infoField;
            }
            set {
                if ((object.ReferenceEquals(this.infoField, value) != true)) {
                    this.infoField = value;
                    this.RaisePropertyChanged("info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string tstamp {
            get {
                return this.tstampField;
            }
            set {
                if ((object.ReferenceEquals(this.tstampField, value) != true)) {
                    this.tstampField = value;
                    this.RaisePropertyChanged("tstamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EventResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string txtdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name_enField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutoEqlink.DuongTest.TeamResult[] listteamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID_Event {
            get {
                return this.ID_EventField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_EventField, value) != true)) {
                    this.ID_EventField = value;
                    this.RaisePropertyChanged("ID_Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string txtday {
            get {
                return this.txtdayField;
            }
            set {
                if ((object.ReferenceEquals(this.txtdayField, value) != true)) {
                    this.txtdayField = value;
                    this.RaisePropertyChanged("txtday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name_en {
            get {
                return this.Name_enField;
            }
            set {
                if ((object.ReferenceEquals(this.Name_enField, value) != true)) {
                    this.Name_enField = value;
                    this.RaisePropertyChanged("Name_en");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AutoEqlink.DuongTest.TeamResult[] listteam {
            get {
                return this.listteamField;
            }
            set {
                if ((object.ReferenceEquals(this.listteamField, value) != true)) {
                    this.listteamField = value;
                    this.RaisePropertyChanged("listteam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeamResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TeamResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teamAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teamBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string teamTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstHalfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FulltimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string teamA {
            get {
                return this.teamAField;
            }
            set {
                if ((object.ReferenceEquals(this.teamAField, value) != true)) {
                    this.teamAField = value;
                    this.RaisePropertyChanged("teamA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string teamB {
            get {
                return this.teamBField;
            }
            set {
                if ((object.ReferenceEquals(this.teamBField, value) != true)) {
                    this.teamBField = value;
                    this.RaisePropertyChanged("teamB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string teamTime {
            get {
                return this.teamTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.teamTimeField, value) != true)) {
                    this.teamTimeField = value;
                    this.RaisePropertyChanged("teamTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstHalf {
            get {
                return this.FirstHalfField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstHalfField, value) != true)) {
                    this.FirstHalfField = value;
                    this.RaisePropertyChanged("FirstHalf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Fulltime {
            get {
                return this.FulltimeField;
            }
            set {
                if ((object.ReferenceEquals(this.FulltimeField, value) != true)) {
                    this.FulltimeField = value;
                    this.RaisePropertyChanged("Fulltime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RaceInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RaceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceIDField;
        
        private int rowidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaceCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string items2enField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string items2cnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RaceID {
            get {
                return this.RaceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceIDField, value) != true)) {
                    this.RaceIDField = value;
                    this.RaisePropertyChanged("RaceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rowid {
            get {
                return this.rowidField;
            }
            set {
                if ((this.rowidField.Equals(value) != true)) {
                    this.rowidField = value;
                    this.RaisePropertyChanged("rowid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RaceCard {
            get {
                return this.RaceCardField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceCardField, value) != true)) {
                    this.RaceCardField = value;
                    this.RaisePropertyChanged("RaceCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RaceCountry {
            get {
                return this.RaceCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.RaceCountryField, value) != true)) {
                    this.RaceCountryField = value;
                    this.RaisePropertyChanged("RaceCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string items2en {
            get {
                return this.items2enField;
            }
            set {
                if ((object.ReferenceEquals(this.items2enField, value) != true)) {
                    this.items2enField = value;
                    this.RaisePropertyChanged("items2en");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string items2cn {
            get {
                return this.items2cnField;
            }
            set {
                if ((object.ReferenceEquals(this.items2cnField, value) != true)) {
                    this.items2cnField = value;
                    this.RaisePropertyChanged("items2cn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DuongTest.ACWSSoap")]
    public interface ACWSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AutoEqlink.DuongTest.HelloWorldResponse HelloWorld(AutoEqlink.DuongTest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.HelloWorldResponse> HelloWorldAsync(AutoEqlink.DuongTest.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataReady", ReplyAction="*")]
        bool IsDataReady();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataReady", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsDataReadyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListCountry", ReplyAction="*")]
        AutoEqlink.DuongTest.getListCountryResponse getListCountry(AutoEqlink.DuongTest.getListCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.getListCountryResponse> getListCountryAsync(AutoEqlink.DuongTest.getListCountryRequest request);
        
        // CODEGEN: Generating message contract since element name ct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCountry", ReplyAction="*")]
        AutoEqlink.DuongTest.UpdateCountryResponse UpdateCountry(AutoEqlink.DuongTest.UpdateCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateCountryResponse> UpdateCountryAsync(AutoEqlink.DuongTest.UpdateCountryRequest request);
        
        // CODEGEN: Generating message contract since element name lst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveLiveToteList1", ReplyAction="*")]
        AutoEqlink.DuongTest.SaveLiveToteList1Response SaveLiveToteList1(AutoEqlink.DuongTest.SaveLiveToteList1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveLiveToteList1", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteList1Response> SaveLiveToteList1Async(AutoEqlink.DuongTest.SaveLiveToteList1Request request);
        
        // CODEGEN: Generating message contract since element name lst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveSoccerResult", ReplyAction="*")]
        AutoEqlink.DuongTest.SaveSoccerResultResponse SaveSoccerResult(AutoEqlink.DuongTest.SaveSoccerResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveSoccerResult", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveSoccerResultResponse> SaveSoccerResultAsync(AutoEqlink.DuongTest.SaveSoccerResultRequest request);
        
        // CODEGEN: Generating message contract since element name lst from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveLiveToteList", ReplyAction="*")]
        AutoEqlink.DuongTest.SaveLiveToteListResponse SaveLiveToteList(AutoEqlink.DuongTest.SaveLiveToteListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveLiveToteList", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteListResponse> SaveLiveToteListAsync(AutoEqlink.DuongTest.SaveLiveToteListRequest request);
        
        // CODEGEN: Generating message contract since element name msg from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        AutoEqlink.DuongTest.SendMessageResponse SendMessage(AutoEqlink.DuongTest.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SendMessageResponse> SendMessageAsync(AutoEqlink.DuongTest.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name ri from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRaceInfo", ReplyAction="*")]
        AutoEqlink.DuongTest.UpdateRaceInfoResponse UpdateRaceInfo(AutoEqlink.DuongTest.UpdateRaceInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRaceInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateRaceInfoResponse> UpdateRaceInfoAsync(AutoEqlink.DuongTest.UpdateRaceInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AutoEqlink.DuongTest.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AutoEqlink.DuongTest.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListCountry", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.getListCountryRequestBody Body;
        
        public getListCountryRequest() {
        }
        
        public getListCountryRequest(AutoEqlink.DuongTest.getListCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getListCountryRequestBody {
        
        public getListCountryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.getListCountryResponseBody Body;
        
        public getListCountryResponse() {
        }
        
        public getListCountryResponse(AutoEqlink.DuongTest.getListCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.ArrayOfCountry getListCountryResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lstF;
        
        public getListCountryResponseBody() {
        }
        
        public getListCountryResponseBody(AutoEqlink.DuongTest.ArrayOfCountry getListCountryResult, string lstF) {
            this.getListCountryResult = getListCountryResult;
            this.lstF = lstF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCountry", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.UpdateCountryRequestBody Body;
        
        public UpdateCountryRequest() {
        }
        
        public UpdateCountryRequest(AutoEqlink.DuongTest.UpdateCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.country ct;
        
        public UpdateCountryRequestBody() {
        }
        
        public UpdateCountryRequestBody(AutoEqlink.DuongTest.country ct) {
            this.ct = ct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.UpdateCountryResponseBody Body;
        
        public UpdateCountryResponse() {
        }
        
        public UpdateCountryResponse(AutoEqlink.DuongTest.UpdateCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateCountryResult;
        
        public UpdateCountryResponseBody() {
        }
        
        public UpdateCountryResponseBody(bool UpdateCountryResult) {
            this.UpdateCountryResult = UpdateCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveLiveToteList1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveLiveToteList1", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveLiveToteList1RequestBody Body;
        
        public SaveLiveToteList1Request() {
        }
        
        public SaveLiveToteList1Request(AutoEqlink.DuongTest.SaveLiveToteList1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveLiveToteList1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.LiveTote[] lst;
        
        public SaveLiveToteList1RequestBody() {
        }
        
        public SaveLiveToteList1RequestBody(AutoEqlink.DuongTest.LiveTote[] lst) {
            this.lst = lst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveLiveToteList1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveLiveToteList1Response", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveLiveToteList1ResponseBody Body;
        
        public SaveLiveToteList1Response() {
        }
        
        public SaveLiveToteList1Response(AutoEqlink.DuongTest.SaveLiveToteList1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveLiveToteList1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveLiveToteList1Result;
        
        public SaveLiveToteList1ResponseBody() {
        }
        
        public SaveLiveToteList1ResponseBody(bool SaveLiveToteList1Result) {
            this.SaveLiveToteList1Result = SaveLiveToteList1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSoccerResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSoccerResult", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveSoccerResultRequestBody Body;
        
        public SaveSoccerResultRequest() {
        }
        
        public SaveSoccerResultRequest(AutoEqlink.DuongTest.SaveSoccerResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSoccerResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.EventResult[] lst;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lang;
        
        public SaveSoccerResultRequestBody() {
        }
        
        public SaveSoccerResultRequestBody(AutoEqlink.DuongTest.EventResult[] lst, string lang) {
            this.lst = lst;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveSoccerResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveSoccerResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveSoccerResultResponseBody Body;
        
        public SaveSoccerResultResponse() {
        }
        
        public SaveSoccerResultResponse(AutoEqlink.DuongTest.SaveSoccerResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveSoccerResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveSoccerResultResult;
        
        public SaveSoccerResultResponseBody() {
        }
        
        public SaveSoccerResultResponseBody(bool SaveSoccerResultResult) {
            this.SaveSoccerResultResult = SaveSoccerResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveLiveToteListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveLiveToteList", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveLiveToteListRequestBody Body;
        
        public SaveLiveToteListRequest() {
        }
        
        public SaveLiveToteListRequest(AutoEqlink.DuongTest.SaveLiveToteListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveLiveToteListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.LiveTote[] lst;
        
        public SaveLiveToteListRequestBody() {
        }
        
        public SaveLiveToteListRequestBody(AutoEqlink.DuongTest.LiveTote[] lst) {
            this.lst = lst;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveLiveToteListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveLiveToteListResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SaveLiveToteListResponseBody Body;
        
        public SaveLiveToteListResponse() {
        }
        
        public SaveLiveToteListResponse(AutoEqlink.DuongTest.SaveLiveToteListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveLiveToteListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveLiveToteListResult;
        
        public SaveLiveToteListResponseBody() {
        }
        
        public SaveLiveToteListResponseBody(bool SaveLiveToteListResult) {
            this.SaveLiveToteListResult = SaveLiveToteListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(AutoEqlink.DuongTest.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string msg;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string msg) {
            this.msg = msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(AutoEqlink.DuongTest.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendMessageResponseBody {
        
        public SendMessageResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRaceInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRaceInfo", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.UpdateRaceInfoRequestBody Body;
        
        public UpdateRaceInfoRequest() {
        }
        
        public UpdateRaceInfoRequest(AutoEqlink.DuongTest.UpdateRaceInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRaceInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AutoEqlink.DuongTest.RaceInfo ri;
        
        public UpdateRaceInfoRequestBody() {
        }
        
        public UpdateRaceInfoRequestBody(AutoEqlink.DuongTest.RaceInfo ri) {
            this.ri = ri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRaceInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRaceInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AutoEqlink.DuongTest.UpdateRaceInfoResponseBody Body;
        
        public UpdateRaceInfoResponse() {
        }
        
        public UpdateRaceInfoResponse(AutoEqlink.DuongTest.UpdateRaceInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRaceInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateRaceInfoResult;
        
        public UpdateRaceInfoResponseBody() {
        }
        
        public UpdateRaceInfoResponseBody(bool UpdateRaceInfoResult) {
            this.UpdateRaceInfoResult = UpdateRaceInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ACWSSoapChannel : AutoEqlink.DuongTest.ACWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ACWSSoapClient : System.ServiceModel.ClientBase<AutoEqlink.DuongTest.ACWSSoap>, AutoEqlink.DuongTest.ACWSSoap {
        
        public ACWSSoapClient() {
        }
        
        public ACWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ACWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ACWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.HelloWorldResponse AutoEqlink.DuongTest.ACWSSoap.HelloWorld(AutoEqlink.DuongTest.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AutoEqlink.DuongTest.HelloWorldRequest inValue = new AutoEqlink.DuongTest.HelloWorldRequest();
            inValue.Body = new AutoEqlink.DuongTest.HelloWorldRequestBody();
            AutoEqlink.DuongTest.HelloWorldResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.HelloWorldResponse> AutoEqlink.DuongTest.ACWSSoap.HelloWorldAsync(AutoEqlink.DuongTest.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.HelloWorldResponse> HelloWorldAsync() {
            AutoEqlink.DuongTest.HelloWorldRequest inValue = new AutoEqlink.DuongTest.HelloWorldRequest();
            inValue.Body = new AutoEqlink.DuongTest.HelloWorldRequestBody();
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public bool IsDataReady() {
            return base.Channel.IsDataReady();
        }
        
        public System.Threading.Tasks.Task<bool> IsDataReadyAsync() {
            return base.Channel.IsDataReadyAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.getListCountryResponse AutoEqlink.DuongTest.ACWSSoap.getListCountry(AutoEqlink.DuongTest.getListCountryRequest request) {
            return base.Channel.getListCountry(request);
        }
        
        public AutoEqlink.DuongTest.ArrayOfCountry getListCountry(out string lstF) {
            AutoEqlink.DuongTest.getListCountryRequest inValue = new AutoEqlink.DuongTest.getListCountryRequest();
            inValue.Body = new AutoEqlink.DuongTest.getListCountryRequestBody();
            AutoEqlink.DuongTest.getListCountryResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).getListCountry(inValue);
            lstF = retVal.Body.lstF;
            return retVal.Body.getListCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.getListCountryResponse> AutoEqlink.DuongTest.ACWSSoap.getListCountryAsync(AutoEqlink.DuongTest.getListCountryRequest request) {
            return base.Channel.getListCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.getListCountryResponse> getListCountryAsync() {
            AutoEqlink.DuongTest.getListCountryRequest inValue = new AutoEqlink.DuongTest.getListCountryRequest();
            inValue.Body = new AutoEqlink.DuongTest.getListCountryRequestBody();
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).getListCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.UpdateCountryResponse AutoEqlink.DuongTest.ACWSSoap.UpdateCountry(AutoEqlink.DuongTest.UpdateCountryRequest request) {
            return base.Channel.UpdateCountry(request);
        }
        
        public bool UpdateCountry(AutoEqlink.DuongTest.country ct) {
            AutoEqlink.DuongTest.UpdateCountryRequest inValue = new AutoEqlink.DuongTest.UpdateCountryRequest();
            inValue.Body = new AutoEqlink.DuongTest.UpdateCountryRequestBody();
            inValue.Body.ct = ct;
            AutoEqlink.DuongTest.UpdateCountryResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).UpdateCountry(inValue);
            return retVal.Body.UpdateCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateCountryResponse> AutoEqlink.DuongTest.ACWSSoap.UpdateCountryAsync(AutoEqlink.DuongTest.UpdateCountryRequest request) {
            return base.Channel.UpdateCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateCountryResponse> UpdateCountryAsync(AutoEqlink.DuongTest.country ct) {
            AutoEqlink.DuongTest.UpdateCountryRequest inValue = new AutoEqlink.DuongTest.UpdateCountryRequest();
            inValue.Body = new AutoEqlink.DuongTest.UpdateCountryRequestBody();
            inValue.Body.ct = ct;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).UpdateCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.SaveLiveToteList1Response AutoEqlink.DuongTest.ACWSSoap.SaveLiveToteList1(AutoEqlink.DuongTest.SaveLiveToteList1Request request) {
            return base.Channel.SaveLiveToteList1(request);
        }
        
        public bool SaveLiveToteList1(AutoEqlink.DuongTest.LiveTote[] lst) {
            AutoEqlink.DuongTest.SaveLiveToteList1Request inValue = new AutoEqlink.DuongTest.SaveLiveToteList1Request();
            inValue.Body = new AutoEqlink.DuongTest.SaveLiveToteList1RequestBody();
            inValue.Body.lst = lst;
            AutoEqlink.DuongTest.SaveLiveToteList1Response retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveLiveToteList1(inValue);
            return retVal.Body.SaveLiveToteList1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteList1Response> AutoEqlink.DuongTest.ACWSSoap.SaveLiveToteList1Async(AutoEqlink.DuongTest.SaveLiveToteList1Request request) {
            return base.Channel.SaveLiveToteList1Async(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteList1Response> SaveLiveToteList1Async(AutoEqlink.DuongTest.LiveTote[] lst) {
            AutoEqlink.DuongTest.SaveLiveToteList1Request inValue = new AutoEqlink.DuongTest.SaveLiveToteList1Request();
            inValue.Body = new AutoEqlink.DuongTest.SaveLiveToteList1RequestBody();
            inValue.Body.lst = lst;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveLiveToteList1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.SaveSoccerResultResponse AutoEqlink.DuongTest.ACWSSoap.SaveSoccerResult(AutoEqlink.DuongTest.SaveSoccerResultRequest request) {
            return base.Channel.SaveSoccerResult(request);
        }
        
        public bool SaveSoccerResult(AutoEqlink.DuongTest.EventResult[] lst, string lang) {
            AutoEqlink.DuongTest.SaveSoccerResultRequest inValue = new AutoEqlink.DuongTest.SaveSoccerResultRequest();
            inValue.Body = new AutoEqlink.DuongTest.SaveSoccerResultRequestBody();
            inValue.Body.lst = lst;
            inValue.Body.lang = lang;
            AutoEqlink.DuongTest.SaveSoccerResultResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveSoccerResult(inValue);
            return retVal.Body.SaveSoccerResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveSoccerResultResponse> AutoEqlink.DuongTest.ACWSSoap.SaveSoccerResultAsync(AutoEqlink.DuongTest.SaveSoccerResultRequest request) {
            return base.Channel.SaveSoccerResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveSoccerResultResponse> SaveSoccerResultAsync(AutoEqlink.DuongTest.EventResult[] lst, string lang) {
            AutoEqlink.DuongTest.SaveSoccerResultRequest inValue = new AutoEqlink.DuongTest.SaveSoccerResultRequest();
            inValue.Body = new AutoEqlink.DuongTest.SaveSoccerResultRequestBody();
            inValue.Body.lst = lst;
            inValue.Body.lang = lang;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveSoccerResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.SaveLiveToteListResponse AutoEqlink.DuongTest.ACWSSoap.SaveLiveToteList(AutoEqlink.DuongTest.SaveLiveToteListRequest request) {
            return base.Channel.SaveLiveToteList(request);
        }
        
        public bool SaveLiveToteList(AutoEqlink.DuongTest.LiveTote[] lst) {
            AutoEqlink.DuongTest.SaveLiveToteListRequest inValue = new AutoEqlink.DuongTest.SaveLiveToteListRequest();
            inValue.Body = new AutoEqlink.DuongTest.SaveLiveToteListRequestBody();
            inValue.Body.lst = lst;
            AutoEqlink.DuongTest.SaveLiveToteListResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveLiveToteList(inValue);
            return retVal.Body.SaveLiveToteListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteListResponse> AutoEqlink.DuongTest.ACWSSoap.SaveLiveToteListAsync(AutoEqlink.DuongTest.SaveLiveToteListRequest request) {
            return base.Channel.SaveLiveToteListAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.SaveLiveToteListResponse> SaveLiveToteListAsync(AutoEqlink.DuongTest.LiveTote[] lst) {
            AutoEqlink.DuongTest.SaveLiveToteListRequest inValue = new AutoEqlink.DuongTest.SaveLiveToteListRequest();
            inValue.Body = new AutoEqlink.DuongTest.SaveLiveToteListRequestBody();
            inValue.Body.lst = lst;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).SaveLiveToteListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.SendMessageResponse AutoEqlink.DuongTest.ACWSSoap.SendMessage(AutoEqlink.DuongTest.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public void SendMessage(string msg) {
            AutoEqlink.DuongTest.SendMessageRequest inValue = new AutoEqlink.DuongTest.SendMessageRequest();
            inValue.Body = new AutoEqlink.DuongTest.SendMessageRequestBody();
            inValue.Body.msg = msg;
            AutoEqlink.DuongTest.SendMessageResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).SendMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.SendMessageResponse> AutoEqlink.DuongTest.ACWSSoap.SendMessageAsync(AutoEqlink.DuongTest.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.SendMessageResponse> SendMessageAsync(string msg) {
            AutoEqlink.DuongTest.SendMessageRequest inValue = new AutoEqlink.DuongTest.SendMessageRequest();
            inValue.Body = new AutoEqlink.DuongTest.SendMessageRequestBody();
            inValue.Body.msg = msg;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutoEqlink.DuongTest.UpdateRaceInfoResponse AutoEqlink.DuongTest.ACWSSoap.UpdateRaceInfo(AutoEqlink.DuongTest.UpdateRaceInfoRequest request) {
            return base.Channel.UpdateRaceInfo(request);
        }
        
        public bool UpdateRaceInfo(AutoEqlink.DuongTest.RaceInfo ri) {
            AutoEqlink.DuongTest.UpdateRaceInfoRequest inValue = new AutoEqlink.DuongTest.UpdateRaceInfoRequest();
            inValue.Body = new AutoEqlink.DuongTest.UpdateRaceInfoRequestBody();
            inValue.Body.ri = ri;
            AutoEqlink.DuongTest.UpdateRaceInfoResponse retVal = ((AutoEqlink.DuongTest.ACWSSoap)(this)).UpdateRaceInfo(inValue);
            return retVal.Body.UpdateRaceInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateRaceInfoResponse> AutoEqlink.DuongTest.ACWSSoap.UpdateRaceInfoAsync(AutoEqlink.DuongTest.UpdateRaceInfoRequest request) {
            return base.Channel.UpdateRaceInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AutoEqlink.DuongTest.UpdateRaceInfoResponse> UpdateRaceInfoAsync(AutoEqlink.DuongTest.RaceInfo ri) {
            AutoEqlink.DuongTest.UpdateRaceInfoRequest inValue = new AutoEqlink.DuongTest.UpdateRaceInfoRequest();
            inValue.Body = new AutoEqlink.DuongTest.UpdateRaceInfoRequestBody();
            inValue.Body.ri = ri;
            return ((AutoEqlink.DuongTest.ACWSSoap)(this)).UpdateRaceInfoAsync(inValue);
        }
    }
}
